class Constants:
	
	DBMODE_TEST = 0
	DBMODE_UAT =  1
	DBMODE_PRODUCTION =  2
	
	REPO_TRANS_STATUS_OPEN = "open"
	REPO_TRANS_STATUS_CLOSE = "closed"
	REPO_TRANS_STATUS_CANCEL = "canceled"
	
	REPO_TRANS_HISTORY_ACTION_OPEN = "open"
	REPO_TRANS_HISTORY_ACTION_CLOSE = "close"
	REPO_TRANS_HISTORY_ACTION_CANCEL = "cancel"
	REPO_TRANS_HISTORY_ACTION_RERATE = "rerate"

	#
	GETREPO_STATUS_OPENCLOSE = "openclose"